/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yujing_serialport_SerialPort */

#ifndef _Included_com_yujing_serialport_SerialPort
#define _Included_com_yujing_serialport_SerialPort

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_yujing_serialport_SerialPort_open(JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_com_yujing_serialport_SerialPort_close(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif
/* Header for class com_yujing_serialport_SerialPort_Builder */

#ifndef _Included_com_yujing_serialport_SerialPort_Builder
#define _Included_com_yujing_serialport_SerialPort_Builder

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif
